In [19]:
import seaborn as sns
import pandas as pd
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

# **Exercise 1**

Use MICE on the life-expectancy dataset

In [20]:
life_exp = pd.read_csv('Life Expectancy Data.csv')
life_exp

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,Zimbabwe,2004,Developing,44.3,723.0,27,4.36,0.000000,68.0,31,...,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2934,Zimbabwe,2003,Developing,44.5,715.0,26,4.06,0.000000,7.0,998,...,7.0,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
2935,Zimbabwe,2002,Developing,44.8,73.0,25,4.43,0.000000,73.0,304,...,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,Zimbabwe,2001,Developing,45.3,686.0,25,1.72,0.000000,76.0,529,...,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,Zimbabwe,2000,Developing,46.0,665.0,24,1.68,0.000000,79.0,1483,...,78.0,7.10,78.0,43.5,547.358878,12222251.0,11.0,11.2,0.434,9.8

In [21]:
print(life_exp.isnull().sum())

Country                              0
Year                                 0
Status                               0
Life expectancy                     10
Adult Mortality                     10
infant deaths                        0
Alcohol                            194
percentage expenditure               0
Hepatitis B                        553
Measles                              0
 BMI                                34
under-five deaths                    0
Polio                               19
Total expenditure                  226
Diphtheria                          19
 HIV/AIDS                            0
GDP                                448
Population                         652
 thinness  1-19 years               34
 thinness 5-9 years                 34
Income composition of resources    167
Schooling                          163
dtype: int64

In [22]:
life_exp_encoded = pd.get_dummies(life_exp, drop_first=True)
life_exp_encoded.head()

,Year,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,...,Country_United States of America,Country_Uruguay,Country_Uzbekistan,Country_Vanuatu,Country_Venezuela (Bolivarian Republic of),Country_Viet Nam,Country_Yemen,Country_Zambia,Country_Zimbabwe,Status_Developing
0,2015,65.0,263.0,62,0.01,71.279624,65.0,1154,19.1,83,...,False,False,False,False,False,False,False,False,False,True
1,2014,59.9,271.0,64,0.01,73.523582,62.0,492,18.6,86,...,False,False,False,False,False,False,False,False,False,True
2,2013,59.9,268.0,66,0.01,73.219243,64.0,430,18.1,89,...,False,False,False,False,False,False,False,False,False,True
3,2012,59.5,272.0,69,0.01,78.184215,67.0,2787,17.6,93,...,False,False,False,False,False,False,False,False,False,True
4,2011,59.2,275.0,71,0.01,7.097109,68.0,3013,17.2,97,...,False,False,False,False,False,False,False,False,False,True

In [23]:
imputer_le = IterativeImputer(max_iter=10, random_state=42)

In [24]:
le_imputed = pd.DataFrame(imputer_le.fit_transform(life_exp_encoded), columns=life_exp_encoded.columns)

In [25]:
print("Datos Originales")
print(life_exp_encoded.head())
print("Datos imputados")
print(le_imputed.head())

Datos Originales
   Year  Life expectancy   Adult Mortality  infant deaths  Alcohol  \
0  2015              65.0            263.0             62     0.01
1  2014              59.9            271.0             64     0.01
2  2013              59.9            268.0             66     0.01
3  2012              59.5            272.0             69     0.01
4  2011              59.2            275.0             71     0.01

   percentage expenditure  Hepatitis B  Measles    BMI   under-five deaths   \
0               71.279624         65.0      1154   19.1                  83
1               73.523582         62.0       492   18.6                  86
2               73.219243         64.0       430   18.1                  89
3               78.184215         67.0      2787   17.6                  93
4                7.097109         68.0      3013   17.2                  97

   ...  Country_United States of America  Country_Uruguay  Country_Uzbekistan  \
0  ...                             False            False               False
1  ...                             False            False               False
2  ...                             False            False               False
3  ...                             False            False               False
4  ...                             False            False               False

   Country_Vanuatu  Country_Venezuela (Bolivarian Republic of)  \
0            False                                       False
1            False                                       False
2            False                                       False
3            False                                       False
4            False                                       False

   Country_Viet Nam  Country_Yemen  Country_Zambia  Country_Zimbabwe  \
0             False          False           False             False
1             False          False           False             False
2             False          False           False             False
3             False          False           False             False
4             False          False           False             False

   Status_Developing
0               True
1               True
2               True
3               True
4               True

[5 rows x 213 columns]
Datos imputados
     Year  Life expectancy   Adult Mortality  infant deaths  Alcohol  \
0  2015.0              65.0            263.0           62.0     0.01
1  2014.0              59.9            271.0           64.0     0.01
2  2013.0              59.9            268.0           66.0     0.01
3  2012.0              59.5            272.0           69.0     0.01
4  2011.0              59.2            275.0           71.0     0.01

   percentage expenditure  Hepatitis B  Measles    BMI   under-five deaths   \
0               71.279624         65.0    1154.0   19.1                83.0
1               73.523582         62.0     492.0   18.6                86.0
2               73.219243         64.0     430.0   18.1                89.0
3               78.184215         67.0    2787.0   17.6                93.0
4                7.097109         68.0    3013.0   17.2                97.0

   ...  Country_United States of America  Country_Uruguay  Country_Uzbekistan  \
0  ...                               0.0              0.0                 0.0
1  ...                               0.0              0.0                 0.0
2  ...                               0.0              0.0                 0.0
3  ...                               0.0              0.0                 0.0
4  ...                               0.0              0.0                 0.0

   Country_Vanuatu  Country_Venezuela (Bolivarian Republic of)  \
0              0.0                                         0.0
1              0.0                                         0.0
2              0.0                                         0.0
3              0.0                                         0.0
4              0.0                                         0.0

   Country_Viet Nam  Country_Yemen  Country_Zambia  Country_Zimbabwe  \
0               0.0            0.0             0.0               0.0
1               0.0            0.0             0.0               0.0
2               0.0            0.0             0.0               0.0
3               0.0            0.0             0.0               0.0
4               0.0            0.0             0.0               0.0

   Status_Developing
0                1.0
1                1.0
2                1.0
3                1.0
4                1.0

[5 rows x 213 columns]

In [26]:
planets = sns.load_dataset('planets')
planets.head()

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [27]:
print(planets.isnull().sum())

method              0
number              0
orbital_period     43
mass              522
distance          227
year                0
dtype: int64

In [28]:
planets_encoded = pd.get_dummies(planets, drop_first=True)
planets_encoded.head()

,number,orbital_period,mass,distance,year,method_Eclipse Timing Variations,method_Imaging,method_Microlensing,method_Orbital Brightness Modulation,method_Pulsar Timing,method_Pulsation Timing Variations,method_Radial Velocity,method_Transit,method_Transit Timing Variations
0,1,269.300,7.10,77.40,2006,False,False,False,False,False,False,True,False,False
1,1,874.774,2.21,56.95,2008,False,False,False,False,False,False,True,False,False
2,1,763.000,2.60,19.84,2011,False,False,False,False,False,False,True,False,False
3,1,326.030,19.40,110.62,2007,False,False,False,False,False,False,True,False,False
4,1,516.220,10.50,119.47,2009,False,False,False,False,False,False,True,False,False

In [29]:
imputer_p = IterativeImputer(max_iter=10, random_state=42)

In [30]:
planets_imputed = pd.DataFrame(imputer_p.fit_transform(planets_encoded), columns=planets_encoded.columns)

/Users/wil/Documents/TEC/AdvancedAI_Python-Stats/.venv/lib/python3.12/site-packages/sklearn/impute/_iterative.py:895: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

In [31]:
print("Datos Originales")
print(planets_encoded.head())
print("Datos imputados")
print(planets_imputed.head())

Datos Originales
   number  orbital_period   mass  distance  year  \
0       1         269.300   7.10     77.40  2006
1       1         874.774   2.21     56.95  2008
2       1         763.000   2.60     19.84  2011
3       1         326.030  19.40    110.62  2007
4       1         516.220  10.50    119.47  2009

   method_Eclipse Timing Variations  method_Imaging  method_Microlensing  \
0                             False           False                False
1                             False           False                False
2                             False           False                False
3                             False           False                False
4                             False           False                False

   method_Orbital Brightness Modulation  method_Pulsar Timing  \
0                                 False                 False
1                                 False                 False
2                                 False                 False
3                                 False                 False
4                                 False                 False

   method_Pulsation Timing Variations  method_Radial Velocity  method_Transit  \
0                               False                    True           False
1                               False                    True           False
2                               False                    True           False
3                               False                    True           False
4                               False                    True           False

   method_Transit Timing Variations
0                             False
1                             False
2                             False
3                             False
4                             False
Datos imputados
   number  orbital_period   mass  distance    year  \
0     1.0         269.300   7.10     77.40  2006.0
1     1.0         874.774   2.21     56.95  2008.0
2     1.0         763.000   2.60     19.84  2011.0
3     1.0         326.030  19.40    110.62  2007.0
4     1.0         516.220  10.50    119.47  2009.0

   method_Eclipse Timing Variations  method_Imaging  method_Microlensing  \
0                               0.0             0.0                  0.0
1                               0.0             0.0                  0.0
2                               0.0             0.0                  0.0
3                               0.0             0.0                  0.0
4                               0.0             0.0                  0.0

   method_Orbital Brightness Modulation  method_Pulsar Timing  \
0                                   0.0                   0.0
1                                   0.0                   0.0
2                                   0.0                   0.0
3                                   0.0                   0.0
4                                   0.0                   0.0

   method_Pulsation Timing Variations  method_Radial Velocity  method_Transit  \
0                                 0.0                     1.0             0.0
1                                 0.0                     1.0             0.0
2                                 0.0                     1.0             0.0
3                                 0.0                     1.0             0.0
4                                 0.0                     1.0             0.0

   method_Transit Timing Variations
0                               0.0
1                               0.0
2                               0.0
3                               0.0
4                               0.0