# Librerias y Archivos

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# Extracción de datos

In [ ]:
path = "/content/drive/MyDrive/Semestres/S7/IA I/M1_Python-Stats/Tarea1/Most Streamed Spotify Songs 2024.csv"

df = pd.read_csv(path, encoding="cp1252")
df.head()

,Track,Album Name,Artist,Release Date,ISRC,All Time Rank,Track Score,Spotify Streams,Spotify Playlist Count,Spotify Playlist Reach,...,SiriusXM Spins,Deezer Playlist Count,Deezer Playlist Reach,Amazon Playlist Count,Pandora Streams,Pandora Track Stations,Soundcloud Streams,Shazam Counts,TIDAL Popularity,Explicit Track
0,MILLION DOLLAR BABY,Million Dollar Baby - Single,Tommy Richman,4/26/2024,QM24S2402528,1,725.4,"390,470,936","30,716","196,631,588",...,684,62.0,"17,598,718",114.0,"18,004,655","22,931","4,818,457","2,669,262",NaN,0
1,Not Like Us,Not Like Us,Kendrick Lamar,5/4/2024,USUG12400910,2,545.9,"323,703,884","28,113","174,597,137",...,3,67.0,"10,422,430",111.0,"7,780,028","28,444","6,623,075","1,118,279",NaN,1
2,i like the way you kiss me,I like the way you kiss me,Artemas,3/19/2024,QZJ842400387,3,538.4,"601,309,283","54,331","211,607,669",...,536,136.0,"36,321,847",172.0,"5,022,621","5,639","7,208,651","5,285,340",NaN,0
3,Flowers,Flowers - Single,Miley Cyrus,1/12/2023,USSM12209777,4,444.9,"2,031,280,633","269,802","136,569,078",...,"2,182",264.0,"24,684,248",210.0,"190,260,277","203,384",NaN,"11,822,942",NaN,0
4,Houdini,Houdini,Eminem,5/31/2024,USUG12403398,5,423.3,"107,034,922","7,223","151,469,874",...,1,82.0,"17,660,624",105.0,"4,493,884","7,006","207,179","457,017",NaN,1

In [ ]:
summary = pd.DataFrame({
    "missing": df.isna().sum(),
    "present": df.notna().sum(),
    "missing_%": (df.isna().mean() * 100).round(2)
}).sort_values("missing", ascending=False)
summary[summary["missing_%"] > 0]

                            missing  present  missing_%
TIDAL Popularity               4600        0     100.00
Soundcloud Streams             3333     1267      72.46
SiriusXM Spins                 2123     2477      46.15
Pandora Track Stations         1268     3332      27.57
TikTok Posts                   1173     3427      25.50
Pandora Streams                1106     3494      24.04
Amazon Playlist Count          1055     3545      22.93
YouTube Playlist Reach         1009     3591      21.93
TikTok Views                    981     3619      21.33
TikTok Likes                    980     3620      21.30
Deezer Playlist Reach           928     3672      20.17
Deezer Playlist Count           921     3679      20.02
Spotify Popularity              804     3796      17.48
Shazam Counts                   577     4023      12.54
Apple Music Playlist Count      561     4039      12.20
AirPlay Spins                   498     4102      10.83
YouTube Likes                   315     4285       6.85
YouTube Views                   308     4292       6.70
Spotify Streams                 113     4487       2.46
Spotify Playlist Reach           72     4528       1.57
Spotify Playlist Count           70     4530       1.52
Artist                            5     4595       0.11

#Limpieza de datos

## Datos faltantes

In [ ]:
#Delete Tidal Popularity and Soundcloud streams as more than 70% of the values are missing, remove ISRC because it doesnt hold any value?

df = df.drop(columns=["TIDAL Popularity", "Soundcloud Streams", "ISRC"], errors="ignore")
df.head()

,Track,Album Name,Artist,Release Date,All Time Rank,Track Score,Spotify Streams,Spotify Playlist Count,Spotify Playlist Reach,Spotify Popularity,...,Apple Music Playlist Count,AirPlay Spins,SiriusXM Spins,Deezer Playlist Count,Deezer Playlist Reach,Amazon Playlist Count,Pandora Streams,Pandora Track Stations,Shazam Counts,Explicit Track
0,MILLION DOLLAR BABY,Million Dollar Baby - Single,Tommy Richman,4/26/2024,1,725.4,"390,470,936","30,716","196,631,588",92.0,...,210.0,"40,975",684,62.0,"17,598,718",114.0,"18,004,655","22,931","2,669,262",0
1,Not Like Us,Not Like Us,Kendrick Lamar,5/4/2024,2,545.9,"323,703,884","28,113","174,597,137",92.0,...,188.0,"40,778",3,67.0,"10,422,430",111.0,"7,780,028","28,444","1,118,279",1
2,i like the way you kiss me,I like the way you kiss me,Artemas,3/19/2024,3,538.4,"601,309,283","54,331","211,607,669",92.0,...,190.0,"74,333",536,136.0,"36,321,847",172.0,"5,022,621","5,639","5,285,340",0
3,Flowers,Flowers - Single,Miley Cyrus,1/12/2023,4,444.9,"2,031,280,633","269,802","136,569,078",85.0,...,394.0,"1,474,799","2,182",264.0,"24,684,248",210.0,"190,260,277","203,384","11,822,942",0
4,Houdini,Houdini,Eminem,5/31/2024,5,423.3,"107,034,922","7,223","151,469,874",88.0,...,182.0,"12,185",1,82.0,"17,660,624",105.0,"4,493,884","7,006","457,017",1

In [ ]:
#Treat Missing Values -> Replace Streaming Data with 0

df[["SiriusXM Spins", "Pandora Track Stations", "TikTok Posts", "Pandora Streams", "Amazon Playlist Count","YouTube Playlist Reach",
    "TikTok Views", "TikTok Likes","Deezer Playlist Reach","Deezer Playlist Count"	,"Spotify Popularity","Shazam Counts",
    "Apple Music Playlist Count","AirPlay Spins", "YouTube Likes","YouTube Views",
    "Spotify Streams","Spotify Playlist Reach","Spotify Playlist Count"]] = df[["SiriusXM Spins", "Pandora Track Stations", "TikTok Posts",
                                                                                "Pandora Streams", "Amazon Playlist Count","YouTube Playlist Reach",
                                                                                "TikTok Views", "TikTok Likes","Deezer Playlist Reach",
                                                                                "Deezer Playlist Count"	,"Spotify Popularity","Shazam Counts",
                                                                                "Apple Music Playlist Count","AirPlay Spins", "YouTube Likes",
                                                                                "YouTube Views","Spotify Streams","Spotify Playlist Reach",
                                                                                "Spotify Playlist Count"]].fillna(0)
df.head()

,Track,Album Name,Artist,Release Date,All Time Rank,Track Score,Spotify Streams,Spotify Playlist Count,Spotify Playlist Reach,Spotify Popularity,...,Apple Music Playlist Count,AirPlay Spins,SiriusXM Spins,Deezer Playlist Count,Deezer Playlist Reach,Amazon Playlist Count,Pandora Streams,Pandora Track Stations,Shazam Counts,Explicit Track
0,MILLION DOLLAR BABY,Million Dollar Baby - Single,Tommy Richman,4/26/2024,1,725.4,"390,470,936","30,716","196,631,588",92.0,...,210.0,"40,975",684,62.0,"17,598,718",114.0,"18,004,655","22,931","2,669,262",0
1,Not Like Us,Not Like Us,Kendrick Lamar,5/4/2024,2,545.9,"323,703,884","28,113","174,597,137",92.0,...,188.0,"40,778",3,67.0,"10,422,430",111.0,"7,780,028","28,444","1,118,279",1
2,i like the way you kiss me,I like the way you kiss me,Artemas,3/19/2024,3,538.4,"601,309,283","54,331","211,607,669",92.0,...,190.0,"74,333",536,136.0,"36,321,847",172.0,"5,022,621","5,639","5,285,340",0
3,Flowers,Flowers - Single,Miley Cyrus,1/12/2023,4,444.9,"2,031,280,633","269,802","136,569,078",85.0,...,394.0,"1,474,799","2,182",264.0,"24,684,248",210.0,"190,260,277","203,384","11,822,942",0
4,Houdini,Houdini,Eminem,5/31/2024,5,423.3,"107,034,922","7,223","151,469,874",88.0,...,182.0,"12,185",1,82.0,"17,660,624",105.0,"4,493,884","7,006","457,017",1

## Tratamiento de duplicados

In [ ]:
# make sure column exists and is stringy
df["Track"] = df["Track"].astype(str)

# rows where Track appears more than once (exact match)
mask = df["Track"].duplicated(keep=False)
dups = (df.loc[mask, ["Track","Artist","Album Name","Release Date"]]
          .sort_values("Track"))
display(dups.head())

# counts per duplicated track
dup_counts = df["Track"].value_counts()
dup_counts = dup_counts[dup_counts > 1].sort_values(ascending=False)
print(f"Found {len(dup_counts)} duplicated track names.")
display(dup_counts.head())

,Track,Artist,Album Name,Release Date
3185,2002,Anne-Marie,Speak Your Mind,1/1/2015
3819,2002,Anne-Marie,NOW That's What I Call Music! 100,7/20/2018
2527,23,Chayce Beckham,23,5/14/2021
3424,23,Mike WiLL Made-It,"23 (feat. Miley Cyrus, Wiz Khalifa & Juicy J) ...",1/1/2013
1350,24K Magic,Bruno Mars,24K Magic,10/7/2016

Found 182 duplicated track names.

Track
Danza Kuduro - Cover         13
Cake By The Ocean - Cover     9
ýýýýýýýýýýýý                  7
ýýýýýý                        6
Alone                         4
Name: count, dtype: int64

In [ ]:
mask = df["Track"].duplicated(keep=False)
dup_rows = df.loc[mask].sort_values("Track")
dup_rows.head()

,Track,Album Name,Artist,Release Date,All Time Rank,Track Score,Spotify Streams,Spotify Playlist Count,Spotify Playlist Reach,Spotify Popularity,...,Apple Music Playlist Count,AirPlay Spins,SiriusXM Spins,Deezer Playlist Count,Deezer Playlist Reach,Amazon Playlist Count,Pandora Streams,Pandora Track Stations,Shazam Counts,Explicit Track
3185,2002,Speak Your Mind,Anne-Marie,1/1/2015,"3,160",24.5,"1,531,490,541","115,663","31,287,443",73.0,...,93.0,"64,453",104,43.0,"424,600",39.0,"47,969,112","52,873","5,500,764",0
3819,2002,NOW That's What I Call Music! 100,Anne-Marie,7/20/2018,"3,807",21.9,0,116,"163,402",0.0,...,0.0,0,0,0.0,0,0.0,0,0,0,0
2527,23,23,Chayce Beckham,5/14/2021,"2,511",28.3,"217,524,988","52,661","12,543,368",69.0,...,23.0,"165,757",0,1.0,577,20.0,"99,882,249","21,221","1,269,712",0
3424,23,"23 (feat. Miley Cyrus, Wiz Khalifa & Juicy J) ...",Mike WiLL Made-It,1/1/2013,"3,409",23.5,"339,514,083","62,118","14,714,742",63.0,...,26.0,"5,802",0,12.0,"40,463",20.0,"205,205,235","501,321","4,621,402",1
1350,24K Magic,24K Magic,Bruno Mars,10/7/2016,"1,340",40.6,"1,425,996,809","175,419","63,087,960",77.0,...,238.0,"240,328",368,153.0,"1,257,927",46.0,"301,404,498","407,873",0,0

In [ ]:
# Canciones iguales vs. Artista diferente
count=0
print("Ejemplos de tracks duplicados con artista diferente:")
duplicate_tracks = df[df.duplicated(subset=['Track'], keep=False)].sort_values(by='Track')
for track_name in duplicate_tracks['Track'].unique():
    artist_count = duplicate_tracks[duplicate_tracks['Track'] == track_name]['Artist'].nunique()
    if artist_count > 1:
        print(f"\nTrack: {track_name}")
        display(duplicate_tracks[duplicate_tracks['Track'] == track_name][['Track', 'Artist', 'Album Name', 'Release Date']].head())
        count += 1
    if count >= 5:
        break

# Canciones y Artista iguales vs. Álbum o Lanzamiento distinto
count=0
print("\nEjemplos de tracks y artista duplicados pero álbum o lanzamiento distinto:")
for track_name in duplicate_tracks['Track'].unique():
    artist_groups = duplicate_tracks[duplicate_tracks['Track'] == track_name].groupby('Artist')
    for artist_name, artist_df in artist_groups:
        if len(artist_df) > 1:
            print(f"\nTrack: {track_name}, Artist: {artist_name}")
            display(artist_df[['Track', 'Artist', 'Album Name', 'Release Date']].head())
            count += 1
    if count >= 5:
        break

Ejemplos de tracks duplicados con artista diferente:

Track: 23

,Track,Artist,Album Name,Release Date
2527,23,Chayce Beckham,23,5/14/2021
3424,23,Mike WiLL Made-It,"23 (feat. Miley Cyrus, Wiz Khalifa & Juicy J) ...",1/1/2013

Track: 911

     Track         Artist Album Name Release Date
2069   911           Sech        911     2/5/2021
2687   911  Fuerza Regida        911   11/30/2022

Track: A Thousand Years

                 Track           Artist        Album Name Release Date
2072  A Thousand Years      Aldy Santos  A Thousand Years    2/27/2017
962   A Thousand Years  Christina Perri  A Thousand Years   10/18/2011

Track: Aesthetic

         Track      Artist Album Name Release Date
113  Aesthetic  Tollan Kim  Aesthetic     3/4/2022
976  Aesthetic        Xilo  Aesthetic    2/14/2020

Track: After Hours

            Track      Artist   Album Name Release Date
1431  After Hours  The Weeknd  After Hours    2/19/2020
1023  After Hours     Kehlani  After Hours     4/4/2024

Ejemplos de tracks y artista duplicados pero álbum o lanzamiento distinto:

Track: 2002, Artist: Anne-Marie

     Track      Artist                         Album Name Release Date
3185  2002  Anne-Marie                    Speak Your Mind     1/1/2015
3819  2002  Anne-Marie  NOW That's What I Call Music! 100    7/20/2018

Track: 24K Magic, Artist: Bruno Mars

,Track,Artist,Album Name,Release Date
1350,24K Magic,Bruno Mars,24K Magic,10/7/2016
1889,24K Magic,Bruno Mars,"NOW That's What I Call Music, Vol. 61",1/27/2017

Track: A Bar Song (Tipsy), Artist: Shaboozey

                  Track     Artist          Album Name Release Date
36   A Bar Song (Tipsy)  Shaboozey  A Bar Song (Tipsy)    4/12/2024
395  A Bar Song (Tipsy)  Shaboozey  A Bar Song (Tipsy)    4/12/2024

Track: About Damn Time, Artist: Lizzo

                Track Artist       Album Name Release Date
3890  About Damn Time  Lizzo          Special    7/15/2022
171   About Damn Time  Lizzo  About Damn Time    4/14/2022

Track: Animals, Artist: Martin Garrix

        Track         Artist                      Album Name Release Date
3953  Animals  Martin Garrix                Animals - Single     1/1/2013
4501  Animals  Martin Garrix  Tremor (Sensation 2014 Anthem)     1/1/2014

In [ ]:
# Canciones con mismo título pero artista diferente
duplicate_tracks_different_artists = df.groupby('Track').filter(lambda x: x['Artist'].nunique() > 1)
display(duplicate_tracks_different_artists.head())

,Track,Album Name,Artist,Release Date,All Time Rank,Track Score,Spotify Streams,Spotify Playlist Count,Spotify Playlist Reach,Spotify Popularity,...,Apple Music Playlist Count,AirPlay Spins,SiriusXM Spins,Deezer Playlist Count,Deezer Playlist Reach,Amazon Playlist Count,Pandora Streams,Pandora Track Stations,Shazam Counts,Explicit Track
3,Flowers,Flowers - Single,Miley Cyrus,1/12/2023,4,444.9,"2,031,280,633","269,802","136,569,078",85.0,...,394.0,"1,474,799","2,182",264.0,"24,684,248",210.0,"190,260,277","203,384","11,822,942",0
4,Houdini,Houdini,Eminem,5/31/2024,5,423.3,"107,034,922","7,223","151,469,874",88.0,...,182.0,"12,185",1,82.0,"17,660,624",105.0,"4,493,884","7,006","457,017",1
8,Danza Kuduro - Cover,ýýýýýýýýýýýýýýýýýýýýý - ýýýýýýýýýýýýýýýýýý -,MUSIC LAB JPN,6/9/2024,9,355.7,"1,653,018,119",1,15,0.0,...,0.0,0,0,0.0,0,0.0,0,0,0,1
19,As It Was,As It Was,Harry Styles,3/31/2022,20,292.0,"3,301,814,535","407,119","169,783,402",87.0,...,455.0,"1,777,811","4,909",330.0,"12,907,852",189.0,"132,624,772","79,909","14,967,379",0
22,Danza Kuduro - Cover,CLUB DE YOKUKIKU YOUGAKU MEDLEY,MUSIC LAB JPN,5/21/2024,23,279.0,"1,655,575,417",10,655,0.0,...,0.0,0,0,0.0,0,0.0,0,0,0,1

In [ ]:
# Mismos artistas y títulos vs. lanzamientos distintos
duplicate_same_artist = df.groupby(['Track', 'Artist']).filter(lambda x: len(x) > 1)

# Priorización
def prioritize_release(group):
    # Nos quedamos con filas originales (no versiones de recopilación, deluxe, video, etc.)
    original_releases = group[~group['Album Name'].str.contains('Now|Deluxe|Single|Official Video', case=False, na=False)]

    # Se da prioridad al lanzamiento original
    if not original_releases.empty:
        return original_releases.sort_values(by='Release Date').iloc[0]
    else:
        return group.sort_values(by='Release Date').iloc[0]

# Aplicación de la priorización a los que comparten mismo título y artista
prioritized_duplicates = duplicate_same_artist.groupby(['Track', 'Artist']).apply(prioritize_release).reset_index(drop=True)

# Nuevo df sin duplicados y con las aplicaciones
duplicate_indices = duplicate_same_artist.index
non_duplicate_df = df.drop(duplicate_indices)

# Se combinan los df sin duplicados
cleaned_df = pd.concat([non_duplicate_df, prioritized_duplicates], ignore_index=True)
df = cleaned_df

display(df.head())
display(df.info())

/tmp/ipython-input-3653703261.py:16: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  prioritized_duplicates = duplicate_same_artist.groupby(['Track', 'Artist']).apply(prioritize_release).reset_index(drop=True)

,Track,Album Name,Artist,Release Date,All Time Rank,Track Score,Spotify Streams,Spotify Playlist Count,Spotify Playlist Reach,Spotify Popularity,...,Apple Music Playlist Count,AirPlay Spins,SiriusXM Spins,Deezer Playlist Count,Deezer Playlist Reach,Amazon Playlist Count,Pandora Streams,Pandora Track Stations,Shazam Counts,Explicit Track
0,MILLION DOLLAR BABY,Million Dollar Baby - Single,Tommy Richman,4/26/2024,1,725.4,"390,470,936","30,716","196,631,588",92.0,...,210.0,"40,975",684,62.0,"17,598,718",114.0,"18,004,655","22,931","2,669,262",0
1,Not Like Us,Not Like Us,Kendrick Lamar,5/4/2024,2,545.9,"323,703,884","28,113","174,597,137",92.0,...,188.0,"40,778",3,67.0,"10,422,430",111.0,"7,780,028","28,444","1,118,279",1
2,i like the way you kiss me,I like the way you kiss me,Artemas,3/19/2024,3,538.4,"601,309,283","54,331","211,607,669",92.0,...,190.0,"74,333",536,136.0,"36,321,847",172.0,"5,022,621","5,639","5,285,340",0
3,Beautiful Things,Beautiful Things,Benson Boone,1/18/2024,7,407.2,"900,158,751","73,118","201,585,714",86.0,...,280.0,"383,478",429,168.0,"48,197,850",154.0,"65,447,476","57,372","9,990,302",0
4,BAND4BAND (feat. Lil Baby),BAND4BAND (feat. Lil Baby),Central Cee,5/23/2024,10,330.6,"90,676,573","10,400","184,199,419",86.0,...,191.0,"3,823",117,78.0,"10,800,098",92.0,"1,005,626",842,"666,302",1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4488 entries, 0 to 4487
Data columns (total 26 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Track                       4488 non-null   object
 1   Album Name                  4488 non-null   object
 2   Artist                      4483 non-null   object
 3   Release Date                4488 non-null   object
 4   All Time Rank               4488 non-null   object
 5   Track Score                 4488 non-null   float64
 6   Spotify Streams             4488 non-null   object
 7   Spotify Playlist Count      4488 non-null   object
 8   Spotify Playlist Reach      4488 non-null   object
 9   Spotify Popularity          4488 non-null   float64
 10  YouTube Views               4488 non-null   object
 11  YouTube Likes               4488 non-null   object
 12  TikTok Posts                4488 non-null   object
 13  TikTok Likes                4488 non-null   object
 14  TikTok Views                4488 non-null   object
 15  YouTube Playlist Reach      4488 non-null   object
 16  Apple Music Playlist Count  4488 non-null   float64
 17  AirPlay Spins               4488 non-null   object
 18  SiriusXM Spins              4488 non-null   object
 19  Deezer Playlist Count       4488 non-null   float64
 20  Deezer Playlist Reach       4488 non-null   object
 21  Amazon Playlist Count       4488 non-null   float64
 22  Pandora Streams             4488 non-null   object
 23  Pandora Track Stations      4488 non-null   object
 24  Shazam Counts               4488 non-null   object
 25  Explicit Track              4488 non-null   int64
dtypes: float64(5), int64(1), object(20)
memory usage: 911.8+ KB

None

In [ ]:
# Duplicados
remaining_duplicates = df[df.duplicated(subset=['Track', 'Artist', 'Album Name'], keep=False)].copy()

# Columnas con posibles 0s (numéricas)
numerical_cols = remaining_duplicates.select_dtypes(include=['float64', 'int64']).columns.tolist()

# 0s por fila
remaining_duplicates['zero_count'] = remaining_duplicates[numerical_cols].apply(lambda row: (row == 0).sum(), axis=1)

# Se orden por frecuencia de 0s y agrupan por duplicados (título - artista - álbum)
prioritized_by_zeros = remaining_duplicates.sort_values(by='zero_count').groupby(['Track', 'Artist', 'Album Name']).head(1)

# Df sin registros duplicados, pero sí priorizados
remaining_duplicate_indices = remaining_duplicates.index
non_remaining_duplicate_df = df.drop(remaining_duplicate_indices)

# Se combina el df limpio
cleaned_df_final = pd.concat([non_remaining_duplicate_df, prioritized_by_zeros.drop(columns='zero_count')], ignore_index=True)
df = cleaned_df_final

display(df.head())
display(df.info())

,Track,Album Name,Artist,Release Date,All Time Rank,Track Score,Spotify Streams,Spotify Playlist Count,Spotify Playlist Reach,Spotify Popularity,...,Apple Music Playlist Count,AirPlay Spins,SiriusXM Spins,Deezer Playlist Count,Deezer Playlist Reach,Amazon Playlist Count,Pandora Streams,Pandora Track Stations,Shazam Counts,Explicit Track
0,MILLION DOLLAR BABY,Million Dollar Baby - Single,Tommy Richman,4/26/2024,1,725.4,"390,470,936","30,716","196,631,588",92.0,...,210.0,"40,975",684,62.0,"17,598,718",114.0,"18,004,655","22,931","2,669,262",0
1,Not Like Us,Not Like Us,Kendrick Lamar,5/4/2024,2,545.9,"323,703,884","28,113","174,597,137",92.0,...,188.0,"40,778",3,67.0,"10,422,430",111.0,"7,780,028","28,444","1,118,279",1
2,i like the way you kiss me,I like the way you kiss me,Artemas,3/19/2024,3,538.4,"601,309,283","54,331","211,607,669",92.0,...,190.0,"74,333",536,136.0,"36,321,847",172.0,"5,022,621","5,639","5,285,340",0
3,Beautiful Things,Beautiful Things,Benson Boone,1/18/2024,7,407.2,"900,158,751","73,118","201,585,714",86.0,...,280.0,"383,478",429,168.0,"48,197,850",154.0,"65,447,476","57,372","9,990,302",0
4,BAND4BAND (feat. Lil Baby),BAND4BAND (feat. Lil Baby),Central Cee,5/23/2024,10,330.6,"90,676,573","10,400","184,199,419",86.0,...,191.0,"3,823",117,78.0,"10,800,098",92.0,"1,005,626",842,"666,302",1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4488 entries, 0 to 4487
Data columns (total 26 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Track                       4488 non-null   object
 1   Album Name                  4488 non-null   object
 2   Artist                      4483 non-null   object
 3   Release Date                4488 non-null   object
 4   All Time Rank               4488 non-null   object
 5   Track Score                 4488 non-null   float64
 6   Spotify Streams             4488 non-null   object
 7   Spotify Playlist Count      4488 non-null   object
 8   Spotify Playlist Reach      4488 non-null   object
 9   Spotify Popularity          4488 non-null   float64
 10  YouTube Views               4488 non-null   object
 11  YouTube Likes               4488 non-null   object
 12  TikTok Posts                4488 non-null   object
 13  TikTok Likes                4488 non-null   object
 14  TikTok Views                4488 non-null   object
 15  YouTube Playlist Reach      4488 non-null   object
 16  Apple Music Playlist Count  4488 non-null   float64
 17  AirPlay Spins               4488 non-null   object
 18  SiriusXM Spins              4488 non-null   object
 19  Deezer Playlist Count       4488 non-null   float64
 20  Deezer Playlist Reach       4488 non-null   object
 21  Amazon Playlist Count       4488 non-null   float64
 22  Pandora Streams             4488 non-null   object
 23  Pandora Track Stations      4488 non-null   object
 24  Shazam Counts               4488 non-null   object
 25  Explicit Track              4488 non-null   int64
dtypes: float64(5), int64(1), object(20)
memory usage: 911.8+ KB

None

In [ ]:
# Título - Artista - Álbum
mask_album = df.duplicated(subset=['Track', 'Artist', 'Album Name'], keep=False)
remaining_duplicates_album = df.loc[mask_album]

# Título - Artista
mask_artist = df.duplicated(subset=['Track', 'Artist'], keep=False)
remaining_duplicates_artist = df.loc[mask_artist]

# Resultados por Título - Artista - Álbum
print("Duplicados por Título - Artista - Álbum:")
display(remaining_duplicates_album)

# Resultados por Título - Artista
print("\nDuplicados por Título - Artista:")
display(remaining_duplicates_artist)

print(f"\nNo. de Duplicados por Título - Artista - Álbum: {len(remaining_duplicates_album)}")
print(f"No. de Duplicados por Título - Artista: {len(remaining_duplicates_artist)}")

Duplicados por Título - Artista - Álbum:

Empty DataFrame
Columns: [Track, Album Name, Artist, Release Date, All Time Rank, Track Score, Spotify Streams, Spotify Playlist Count, Spotify Playlist Reach, Spotify Popularity, YouTube Views, YouTube Likes, TikTok Posts, TikTok Likes, TikTok Views, YouTube Playlist Reach, Apple Music Playlist Count, AirPlay Spins, SiriusXM Spins, Deezer Playlist Count, Deezer Playlist Reach, Amazon Playlist Count, Pandora Streams, Pandora Track Stations, Shazam Counts, Explicit Track]
Index: []

[0 rows x 26 columns]

Duplicados por Título - Artista:

Empty DataFrame
Columns: [Track, Album Name, Artist, Release Date, All Time Rank, Track Score, Spotify Streams, Spotify Playlist Count, Spotify Playlist Reach, Spotify Popularity, YouTube Views, YouTube Likes, TikTok Posts, TikTok Likes, TikTok Views, YouTube Playlist Reach, Apple Music Playlist Count, AirPlay Spins, SiriusXM Spins, Deezer Playlist Count, Deezer Playlist Reach, Amazon Playlist Count, Pandora Streams, Pandora Track Stations, Shazam Counts, Explicit Track]
Index: []

[0 rows x 26 columns]

No. de Duplicados por Título - Artista - Álbum: 0
No. de Duplicados por Título - Artista: 0

##Datos Numéricos y Categóricos (Encoding)

In [ ]:
columns_to_convert = [
    'All Time Rank',

    'Spotify Streams',
    'Spotify Playlist Count',
    'Spotify Playlist Reach',

    'YouTube Views',
    'YouTube Likes',
    'YouTube Playlist Reach',

    'TikTok Posts',
    'TikTok Likes',
    'TikTok Views',

    'AirPlay Spins', 'SiriusXM Spins', 'Deezer Playlist Reach',
    'Pandora Streams',
    'Pandora Track Stations',

    'Shazam Counts'
]

for col in columns_to_convert:
    if col in df.columns and df[col].dtype == 'object':
        # Quitamos comas y pasamos a num, posibles nans se reemplazan por 0 otra vez
        df[col] = pd.to_numeric(df[col].astype(str).str.replace(',', ''), errors='coerce')
        df[col] = df[col].fillna(0)

display(df.info())
display(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4488 entries, 0 to 4487
Data columns (total 26 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Track                       4488 non-null   object
 1   Album Name                  4488 non-null   object
 2   Artist                      4483 non-null   object
 3   Release Date                4488 non-null   object
 4   All Time Rank               4488 non-null   int64
 5   Track Score                 4488 non-null   float64
 6   Spotify Streams             4488 non-null   int64
 7   Spotify Playlist Count      4488 non-null   int64
 8   Spotify Playlist Reach      4488 non-null   int64
 9   Spotify Popularity          4488 non-null   float64
 10  YouTube Views               4488 non-null   int64
 11  YouTube Likes               4488 non-null   int64
 12  TikTok Posts                4488 non-null   int64
 13  TikTok Likes                4488 non-null   int64
 14  TikTok Views                4488 non-null   int64
 15  YouTube Playlist Reach      4488 non-null   int64
 16  Apple Music Playlist Count  4488 non-null   float64
 17  AirPlay Spins               4488 non-null   int64
 18  SiriusXM Spins              4488 non-null   int64
 19  Deezer Playlist Count       4488 non-null   float64
 20  Deezer Playlist Reach       4488 non-null   int64
 21  Amazon Playlist Count       4488 non-null   float64
 22  Pandora Streams             4488 non-null   int64
 23  Pandora Track Stations      4488 non-null   int64
 24  Shazam Counts               4488 non-null   int64
 25  Explicit Track              4488 non-null   int64
dtypes: float64(5), int64(17), object(4)
memory usage: 911.8+ KB

None

,Track,Album Name,Artist,Release Date,All Time Rank,Track Score,Spotify Streams,Spotify Playlist Count,Spotify Playlist Reach,Spotify Popularity,...,Apple Music Playlist Count,AirPlay Spins,SiriusXM Spins,Deezer Playlist Count,Deezer Playlist Reach,Amazon Playlist Count,Pandora Streams,Pandora Track Stations,Shazam Counts,Explicit Track
0,MILLION DOLLAR BABY,Million Dollar Baby - Single,Tommy Richman,4/26/2024,1,725.4,390470936,30716,196631588,92.0,...,210.0,40975,684,62.0,17598718,114.0,18004655,22931,2669262,0
1,Not Like Us,Not Like Us,Kendrick Lamar,5/4/2024,2,545.9,323703884,28113,174597137,92.0,...,188.0,40778,3,67.0,10422430,111.0,7780028,28444,1118279,1
2,i like the way you kiss me,I like the way you kiss me,Artemas,3/19/2024,3,538.4,601309283,54331,211607669,92.0,...,190.0,74333,536,136.0,36321847,172.0,5022621,5639,5285340,0
3,Beautiful Things,Beautiful Things,Benson Boone,1/18/2024,7,407.2,900158751,73118,201585714,86.0,...,280.0,383478,429,168.0,48197850,154.0,65447476,57372,9990302,0
4,BAND4BAND (feat. Lil Baby),BAND4BAND (feat. Lil Baby),Central Cee,5/23/2024,10,330.6,90676573,10400,184199419,86.0,...,191.0,3823,117,78.0,10800098,92.0,1005626,842,666302,1

In [ ]:
# Conversión a fecha y extracción del mes y año (ints) del release
df['Release Date'] = pd.to_datetime(df['Release Date'], errors='coerce')
df['Release Month'] = df['Release Date'].dt.month
df['Release Year'] = df['Release Date'].dt.year

# Se busca evitar que el modelo memorice fechas y, en su lugar, trate de comprender relaciones entre artistas, tracks, por fecha (verano, mes, año)
df = df.drop(columns=['Release Date'])

display(df.info())
display(df.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4488 entries, 0 to 4487
Data columns (total 27 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Track                       4488 non-null   object
 1   Album Name                  4488 non-null   object
 2   Artist                      4483 non-null   object
 3   All Time Rank               4488 non-null   int64
 4   Track Score                 4488 non-null   float64
 5   Spotify Streams             4488 non-null   int64
 6   Spotify Playlist Count      4488 non-null   int64
 7   Spotify Playlist Reach      4488 non-null   int64
 8   Spotify Popularity          4488 non-null   float64
 9   YouTube Views               4488 non-null   int64
 10  YouTube Likes               4488 non-null   int64
 11  TikTok Posts                4488 non-null   int64
 12  TikTok Likes                4488 non-null   int64
 13  TikTok Views                4488 non-null   int64
 14  YouTube Playlist Reach      4488 non-null   int64
 15  Apple Music Playlist Count  4488 non-null   float64
 16  AirPlay Spins               4488 non-null   int64
 17  SiriusXM Spins              4488 non-null   int64
 18  Deezer Playlist Count       4488 non-null   float64
 19  Deezer Playlist Reach       4488 non-null   int64
 20  Amazon Playlist Count       4488 non-null   float64
 21  Pandora Streams             4488 non-null   int64
 22  Pandora Track Stations      4488 non-null   int64
 23  Shazam Counts               4488 non-null   int64
 24  Explicit Track              4488 non-null   int64
 25  Release Month               4488 non-null   int32
 26  Release Year                4488 non-null   int32
dtypes: float64(5), int32(2), int64(17), object(3)
memory usage: 911.8+ KB

None

,Track,Album Name,Artist,All Time Rank,Track Score,Spotify Streams,Spotify Playlist Count,Spotify Playlist Reach,Spotify Popularity,YouTube Views,...,SiriusXM Spins,Deezer Playlist Count,Deezer Playlist Reach,Amazon Playlist Count,Pandora Streams,Pandora Track Stations,Shazam Counts,Explicit Track,Release Month,Release Year
0,MILLION DOLLAR BABY,Million Dollar Baby - Single,Tommy Richman,1,725.4,390470936,30716,196631588,92.0,84274754,...,684,62.0,17598718,114.0,18004655,22931,2669262,0,4,2024
1,Not Like Us,Not Like Us,Kendrick Lamar,2,545.9,323703884,28113,174597137,92.0,116347040,...,3,67.0,10422430,111.0,7780028,28444,1118279,1,5,2024
2,i like the way you kiss me,I like the way you kiss me,Artemas,3,538.4,601309283,54331,211607669,92.0,122599116,...,536,136.0,36321847,172.0,5022621,5639,5285340,0,3,2024
3,Beautiful Things,Beautiful Things,Benson Boone,7,407.2,900158751,73118,201585714,86.0,308723145,...,429,168.0,48197850,154.0,65447476,57372,9990302,0,1,2024
4,BAND4BAND (feat. Lil Baby),BAND4BAND (feat. Lil Baby),Central Cee,10,330.6,90676573,10400,184199419,86.0,32735244,...,117,78.0,10800098,92.0,1005626,842,666302,1,5,2024

In [ ]:
# Datos ordenados por artista, año y mes
df_sorted = df.sort_values(by=['Artist', 'Release Year', 'Release Month'])
display(df_sorted.head())

,Track,Album Name,Artist,All Time Rank,Track Score,Spotify Streams,Spotify Playlist Count,Spotify Playlist Reach,Spotify Popularity,YouTube Views,...,SiriusXM Spins,Deezer Playlist Count,Deezer Playlist Reach,Amazon Playlist Count,Pandora Streams,Pandora Track Stations,Shazam Counts,Explicit Track,Release Month,Release Year
2243,Come and Say - Original Mix,Relyt Conections 3,"""XY""",2379,29.2,0,1,9,0.0,415159148,...,0,0.0,0,0.0,0,0,0,0,11,2022
3131,"ZEIT, DASS SICH WAS DREHT","ZEIT, DASS SICH WAS DREHT",$OHO BANI,3291,23.9,54065563,7779,9672092,73.0,6744201,...,0,16.0,9108102,16.0,0,0,198646,1,2,2024
4386,For the Last Time,For the Last Time,$uicideboy$,4585,19.4,305049963,65770,5103054,71.0,149247747,...,0,2.0,14217,0.0,20104066,13184,656337,1,9,2017
1606,"...And to Those I Love, Thanks for Sticking Ar...",STOP STARING AT THE SHADOWS,$uicideboy$,1709,35.3,675082623,167727,15198984,73.0,269460083,...,0,5.0,22406,0.0,11746442,31117,3195912,1,2,2020
3563,Avalon,Avalon,$uicideboy$,3723,22.2,204669341,54797,3940409,65.0,49001959,...,0,0.0,0,0.0,4218125,3630,288456,1,5,2021

In [ ]:
# Hay artistas nulos, pero no cuentan con registros. Se eliminan (5 / 4888) = 0.102% de la data
df_sorted = df_sorted.dropna(subset=['Artist'])
display(df_sorted.head())

,Track,Album Name,Artist,All Time Rank,Track Score,Spotify Streams,Spotify Playlist Count,Spotify Playlist Reach,Spotify Popularity,YouTube Views,...,SiriusXM Spins,Deezer Playlist Count,Deezer Playlist Reach,Amazon Playlist Count,Pandora Streams,Pandora Track Stations,Shazam Counts,Explicit Track,Release Month,Release Year
2243,Come and Say - Original Mix,Relyt Conections 3,"""XY""",2379,29.2,0,1,9,0.0,415159148,...,0,0.0,0,0.0,0,0,0,0,11,2022
3131,"ZEIT, DASS SICH WAS DREHT","ZEIT, DASS SICH WAS DREHT",$OHO BANI,3291,23.9,54065563,7779,9672092,73.0,6744201,...,0,16.0,9108102,16.0,0,0,198646,1,2,2024
4386,For the Last Time,For the Last Time,$uicideboy$,4585,19.4,305049963,65770,5103054,71.0,149247747,...,0,2.0,14217,0.0,20104066,13184,656337,1,9,2017
1606,"...And to Those I Love, Thanks for Sticking Ar...",STOP STARING AT THE SHADOWS,$uicideboy$,1709,35.3,675082623,167727,15198984,73.0,269460083,...,0,5.0,22406,0.0,11746442,31117,3195912,1,2,2020
3563,Avalon,Avalon,$uicideboy$,3723,22.2,204669341,54797,3940409,65.0,49001959,...,0,0.0,0,0.0,4218125,3630,288456,1,5,2021

In [ ]:
cols_with_zero = []

for col in df.columns:
  if 0 in df[col].unique():
    cols_with_zero += [col]

# Se imputa mediana móvil artista por artista con window de 5 y 1 minperiod para calcular hasta primeras entradas.
for col in cols_with_zero[:-1]:
    rolling_median = df_sorted.groupby('Artist')[col].transform(lambda x: x.rolling(window=5, min_periods=1).median())

    # Imputación de valores SI Y SOLO SI la mediana móvil no es 0.
    df_sorted[col] = df_sorted.apply(lambda row: rolling_median[row.name] if row[col] == 0 and rolling_median[row.name] != 0 else row[col],
                                     axis=1)

In [ ]:
artists_mean = df.groupby(['Artist'])[cols_with_zero[:-1]].mean().reset_index()

# Se asignará una media a cada artista por reproducciones, impacto en playlists, likes, spins y views
streams_cols = []
playlist_count_cols = []
playlist_reach_cols = []
likes_cols = []
views_cols = []
spins_cols = []

for col in artists_mean.columns:
  if "Streams" in col:
    streams_cols += [col]
  elif "Playlist Count" in col:
    playlist_count_cols += [col]
  elif "Playlist Reach" in col:
    playlist_reach_cols += [col]
  elif "Likes" in col:
    likes_cols += [col]
  elif "Views" in col:
    views_cols += [col]
  elif "Spins" in col:
    spins_cols += [col]

In [ ]:
artists_mean['Streams Mean'] = artists_mean[streams_cols].mean(axis=1)
artists_mean['Playlist Count Mean'] = artists_mean[playlist_count_cols].mean(axis=1)
artists_mean['Playlist Reach Mean'] = artists_mean[playlist_reach_cols].mean(axis=1)
artists_mean['Likes Mean'] = artists_mean[likes_cols].mean(axis=1)
artists_mean['Views Mean'] = artists_mean[views_cols].mean(axis=1)
artists_mean['Spins Mean'] = artists_mean[spins_cols].mean(axis=1)

artists_mean.head()

,Artist,Spotify Streams,Spotify Playlist Count,Spotify Playlist Reach,Spotify Popularity,YouTube Views,YouTube Likes,TikTok Posts,TikTok Likes,TikTok Views,...,Amazon Playlist Count,Pandora Streams,Pandora Track Stations,Shazam Counts,Streams Mean,Playlist Count Mean,Playlist Reach Mean,Likes Mean,Views Mean,Spins Mean
0,"""XY""",0.0,1.000000,9.000000e+00,0.00,4.151591e+08,745345.00,0.000000,0.00,0.000000e+00,...,0.000000,0.00,0.000000,0.00,0.000000e+00,0.250000,3.000000e+00,372672.50,2.075796e+08,0.500000
1,$OHO BANI,54065563.0,7779.000000,9.672092e+06,73.00,6.744201e+06,72802.00,0.000000,0.00,0.000000e+00,...,16.000000,0.00,0.000000,198646.00,2.703278e+07,1957.250000,3.620189e+07,36401.00,3.372100e+06,3868.000000
2,$uicideboy$,188605270.0,46010.555556,6.602650e+06,63.00,7.677397e+07,822896.00,57353.111111,9693052.00,6.303016e+07,...,1.222222,6035940.00,6360.666667,552413.00,9.732060e+07,11504.305556,5.401637e+06,5257974.00,6.990206e+07,98.166667
3,&ME,34601626.0,34272.000000,1.491486e+07,65.00,0.000000e+00,0.00,623.000000,60724.00,8.694440e+05,...,21.000000,0.00,0.000000,989728.00,1.730081e+07,8580.500000,4.984501e+06,30362.00,4.347220e+05,79.000000
4,(G)I-DLE,219234613.0,20092.000000,9.513365e+06,51.25,3.013097e+08,3264112.75,112459.250000,72188496.75,5.635451e+08,...,21.750000,524940.75,1366.000000,446183.75,1.098798e+08,5033.562500,1.979933e+08,37726304.75,4.324274e+08,1427.625000

In [ ]:
artists_mean = artists_mean.drop(columns=streams_cols + playlist_count_cols + playlist_reach_cols + likes_cols + views_cols + spins_cols)

In [ ]:
artists_mean = df.groupby(['Artist'])[["Spotify Playlist Count", "Spotify Playlist Reach", "Apple Music Playlist Count",
                                       "Deezer Playlist Count"]].mean().reset_index()
artists_mean = artists_mean.sort_values(by=["Spotify Playlist Count", "Spotify Playlist Reach", "Apple Music Playlist Count",
                                       "Deezer Playlist Count"], ascending=True)
artists_mean.head()

,Artist,Spotify Playlist Count,Spotify Playlist Reach,Apple Music Playlist Count,Deezer Playlist Count
14,3 Palavrinhas,0.0,0.0,0.0,0.0
177,Baby Flaco,0.0,0.0,0.0,0.0
253,Bonnie Kimmel,0.0,0.0,0.0,0.0
254,BoomBoxRepairKit,0.0,0.0,0.0,0.0
283,CA3RD,0.0,0.0,0.0,0.0

In [ ]:
artists_labels = {}

for i, artist in enumerate(artists_mean['Artist']):
  artists_labels[artist] = i

In [ ]:
df['Artist'] = df['Artist'].map(artists_labels)
df.head()

,Track,Album Name,Artist,All Time Rank,Track Score,Spotify Streams,Spotify Playlist Count,Spotify Playlist Reach,Spotify Popularity,YouTube Views,...,SiriusXM Spins,Deezer Playlist Count,Deezer Playlist Reach,Amazon Playlist Count,Pandora Streams,Pandora Track Stations,Shazam Counts,Explicit Track,Release Month,Release Year
0,MILLION DOLLAR BABY,Million Dollar Baby - Single,931.0,1,725.4,390470936,30716,196631588,92.0,84274754,...,684,62.0,17598718,114.0,18004655,22931,2669262,0,4,2024
1,Not Like Us,Not Like Us,1800.0,2,545.9,323703884,28113,174597137,92.0,116347040,...,3,67.0,10422430,111.0,7780028,28444,1118279,1,5,2024
2,i like the way you kiss me,I like the way you kiss me,1272.0,3,538.4,601309283,54331,211607669,92.0,122599116,...,536,136.0,36321847,172.0,5022621,5639,5285340,0,3,2024
3,Beautiful Things,Beautiful Things,1388.0,7,407.2,900158751,73118,201585714,86.0,308723145,...,429,168.0,48197850,154.0,65447476,57372,9990302,0,1,2024
4,BAND4BAND (feat. Lil Baby),BAND4BAND (feat. Lil Baby),1615.0,10,330.6,90676573,10400,184199419,86.0,32735244,...,117,78.0,10800098,92.0,1005626,842,666302,1,5,2024

In [ ]:
album_labels = {}
tracks_labels = {}

In [ ]:
grouped_albums = df.groupby(['Artist', 'Album Name'])[["Spotify Playlist Count",
                                                       "Spotify Playlist Reach",
                                                       "Apple Music Playlist Count",
                                                       "Deezer Playlist Count"]].mean().reset_index().sort_values(
                                                           by=["Spotify Playlist Count",
                                                               "Spotify Playlist Reach",
                                                               "Apple Music Playlist Count",
                                                               "Deezer Playlist Count"], ascending=True)
grouped_songs = df.groupby(['Artist', 'Track'])[["Spotify Playlist Count",
                                                 "Spotify Playlist Reach",
                                                 "Apple Music Playlist Count",
                                                 "Deezer Playlist Count"]].mean().reset_index().sort_values(
                                                     by=["Spotify Playlist Count",
                                                         "Spotify Playlist Reach",
                                                         "Apple Music Playlist Count",
                                                         "Deezer Playlist Count"], ascending=True)

In [ ]:
for artist in grouped_albums['Artist'].unique():
  artist_albums = grouped_albums[grouped_albums['Artist']==artist]
  for i, album in enumerate(artist_albums['Album Name'].unique()):
    album_labels[album] = i

df['Album Name'] = df['Album Name'].map(album_labels)

for artist in grouped_songs['Artist'].unique():
  artist_songs = grouped_songs[grouped_songs['Artist']==artist]
  for i, track in enumerate(artist_songs['Track'].unique()):
    tracks_labels[track] = i

df['Track'] = df['Track'].map(tracks_labels)
df.head()

,Track,Album Name,Artist,All Time Rank,Track Score,Spotify Streams,Spotify Playlist Count,Spotify Playlist Reach,Spotify Popularity,YouTube Views,...,SiriusXM Spins,Deezer Playlist Count,Deezer Playlist Reach,Amazon Playlist Count,Pandora Streams,Pandora Track Stations,Shazam Counts,Explicit Track,Release Month,Release Year
0,1.0,0.0,931.0,1,725.4,390470936,30716,196631588,92.0,84274754,...,684,62.0,17598718,114.0,18004655,22931,2669262,0,4,2024
1,2.0,2.0,1800.0,2,545.9,323703884,28113,174597137,92.0,116347040,...,3,67.0,10422430,111.0,7780028,28444,1118279,1,5,2024
2,1.0,1.0,1272.0,3,538.4,601309283,54331,211607669,92.0,122599116,...,536,136.0,36321847,172.0,5022621,5639,5285340,0,3,2024
3,3.0,3.0,1388.0,7,407.2,900158751,73118,201585714,86.0,308723145,...,429,168.0,48197850,154.0,65447476,57372,9990302,0,1,2024
4,1.0,1.0,1615.0,10,330.6,90676573,10400,184199419,86.0,32735244,...,117,78.0,10800098,92.0,1005626,842,666302,1,5,2024

#  Descriptive Statistics Analysis

## Visualizing Data Distributions

In [ ]:
plt.figure()
plt.hist(df['Spotify Streams'], bins='auto', color='green', edgecolor='black')
plt.title('Spotify Streams')
plt.xlabel('Streams')
plt.ylabel('Frecuencia de canciones')
plt.show()

En este histograma podemos observar que la mayor parte de las canciones de spotify son reproducidas muy pocas veces, esto se muestra en el pico que tenemos en nuestro primer grupo que esta cerca del 0 lo que nos indica que existe una gran cantidad de canciones que no son famosas.

Mientras las reproducciones aumentan podemos que la caida es ligeramente "constante", a exepción del segundo grupo donde el número de canciones cae casi a la mitad, lo que nos da a enteder que las canciones más populares son muy pocas. Podemos asumir que las canciones que se encuentran de lado derecho son de artistas importantes o canciones emblemáticas.

In [ ]:
plt.figure()
plt.hist(df['YouTube Views'], bins=50, color='red', edgecolor='black')
plt.title('Youtbe Views')
plt.xlabel('Vistas de videos')
plt.ylabel('Frecuencia de videos')
plt.show()

El histograma de vistas de Youtube tiene un comportamiento muy similar al de Spotify; el pico de lado izquierdo nos muestra que la mayor parte de los videos musicales tiene muy pocas vistas.

Sin embargo a diferencia de Spotify podemos ver una caida abrupta de más de la mitad en la cantidad de videos virales pasando de alrededor de 3,500 a solo 600 vistas aproximadamente.
Conforme aumentan las vistas podemos ver que el número de videos dismunuye cada vez más hasta el punto en el que no se alcanzan a ver los valores de lado izquierdo. Indicando que son muy pocos los videos musicales que alcanzan a tener una popularidad enorme y que a comparación de Spotify es mucho más dificil tener vistas en los videos que reproducciones en las canciones.

##Measures of Central Tendency

In [ ]:
plt.figure()
plt.boxplot(df['Spotify Streams'], orientation='horizontal')
plt.title('Spotify Streams')
plt.xlabel('Streams')
plt.show()

print(f"Spotify Streams\nMedia: {df['Spotify Streams'].mean():.2f}\nMediana: {df['Spotify Streams'].median()}")

In [ ]:
plt.figure()
plt.boxplot(df['YouTube Views'], orientation='horizontal')
plt.title('Youtube Views')
plt.xlabel('Views')
plt.show()

print(f"Youtube Views\nMedia: {df['YouTube Views'].mean():.2f}\nMediana: {df['YouTube Views'].median()}")

Como podemos ver en ambos boxplot la mediana, linea naranja, se mantiene cerca del centro de donde se junta la mayor cantidad de datos por que para obtenerla se deben de ordenar los números de mayor a menor y se toma el número que tenemos en medio de toda esta lista, este número nunca se verá afectado por las anomalias.

Mientras tanto la media es muy suceptible a las anomalias ya que estas pueden cambiar drasticamente su valor; como podemos ver en las gráficas a pesar de que tenemos la mayor cantidad de datos recargados de lado derecho tenemos una cantidad considerable de anomalias de lado izquierdo con valores mucho más grandes, gracias a los datos recargados de lado derecho es que nuestra media también se mueve a la derecha.

## Measures of Dispersion and Relative Variability

In [1]:
# Desviación estándar
std_popularity = df["Spotify Popularity"].std()
std_streams = df["Spotify Streams"].std()
std_views = df["YouTube Views"].std()

# Media de popularity (para CV)
mean_popularity = df["Spotify Popularity"].mean()
mean_streams = df["Spotify Streams"].mean()
mean_views = df["Youtube Views"].mean()

# Coeficiente de variación (CV = std / mean)
cv_popularity = (std_popularity / mean_popularity) * 100
cv_streams = (std_streams / mean_streams) * 100
cv_views = (std_views / mean_views) * 100

print("\nStandard Deviation:")
print("Spotify Popularity:", std_popularity)
print("Spotify Streams:", std_streams)
print("YouTube Views:", std_views)

print("\nCoefficient of Variation (CV):")
print("Spotify Popularity: %", cv_popularity)
print("Spotify Streams: %", cv_streams)
print("YouTube Views: %", cv_views)

NameError: name 'df' is not defined

In [ ]:
plt.figure()
plt.bar(['Spotify Popularity', 'Spotify Streams', 'YouTube Views'], [cv_popularity, cv_streams, cv_views])
plt.title('Coeficientes de variación')
plt.ylabel('Coeficiente de Variación')
plt.show()

Como podemos ver en la gráfica de barras nuestros coeficientes tiene diferentes porcentajes, siendo la popularidad en Spotify la más pequeña con un CV de 52.73%, lo que nos indica que la probabilidad de que una canción sea popular es algo equitativa.

En Spotify streams podemos ver un brinco de un poco más del doble, lo que nos indica que existe una mayor variedad de posibles resultados para una canción, es decir, se vuelve muy complejo calcular si una canción tendrá muchos Streams o no, demostrando el dominio que tienen pocas canciones.

Por ultimo, podemos ver que el CV de Youtube es el más alto de todos. Relacionandolo con el comportamiento de las gráficas de arriba podemos concluir que la competencia de videos musicales es mucho mas agresiva/competitiva a diferencia de Spotify.

#Probabilistic Analysis with Bayes' Theorem

##  Defining Events

In [ ]:
df['Has_High_Popularity'] = (df['Spotify Popularity'] >= 85).astype(int)
df['Is_Explicit'] = (df['Explicit Track'] == 1).astype(int)
df

,Track,Album Name,Artist,All Time Rank,Track Score,Spotify Streams,Spotify Playlist Count,Spotify Playlist Reach,Spotify Popularity,YouTube Views,...,Deezer Playlist Reach,Amazon Playlist Count,Pandora Streams,Pandora Track Stations,Shazam Counts,Explicit Track,Release Month,Release Year,Has_High_Popularity,Is_Explicit
0,1.0,0.0,931.0,1,725.4,390470936,30716,196631588,92.0,84274754,...,17598718,114.0,18004655,22931,2669262,0,4,2024,1,0
1,2.0,2.0,1800.0,2,545.9,323703884,28113,174597137,92.0,116347040,...,10422430,111.0,7780028,28444,1118279,1,5,2024,1,1
2,1.0,1.0,1272.0,3,538.4,601309283,54331,211607669,92.0,122599116,...,36321847,172.0,5022621,5639,5285340,0,3,2024,1,0
3,3.0,3.0,1388.0,7,407.2,900158751,73118,201585714,86.0,308723145,...,48197850,154.0,65447476,57372,9990302,0,1,2024,1,0
4,1.0,1.0,1615.0,10,330.6,90676573,10400,184199419,86.0,32735244,...,10800098,92.0,1005626,842,666302,1,5,2024,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4483,3.0,1.0,1410.0,831,53.2,58469975,7073,108431155,82.0,4436805,...,0,0.0,0,0,0,1,5,2024,0,1
4484,8.0,4.0,1630.0,87,164.8,428233003,57311,144298748,0.0,105148629,...,4037475,60.0,16802867,11821,2490071,1,1,2024,0,1
4485,7.0,4.0,1688.0,138,128.9,998964097,90793,87801398,18.0,113450524,...,5239925,128.0,28318435,67590,4872257,1,6,2023,0,1
4486,4.0,1.0,1566.0,199,107.5,416813996,22468,101875097,0.0,115105080,...,6747701,92.0,3441709,3255,1028262,1,1,2024,0,1
4487,1.0,1.0,1444.0,2855,26.1,311307250,48587,6777195,61.0,460930832,...,20773,7.0,1427765,827,556492,0,1,2021,0,0

##Calculating Prior Probabilities

In [ ]:

p_A = df["Has_High_Popularity"].mean()
p_B = df["Explicit Track"].mean()
p_A_given_B = df.loc[df["Explicit Track"] == 1, "Has_High_Popularity"].mean()

print("P(A)  =", p_A)
print("P(B)  =", p_B)
print("P(A|B) =", p_A_given_B)

P(A)  = 0.011140819964349376
P(B)  = 0.3589572192513369
P(A|B) = 0.00931098696461825

# Applying Bayes' Theorem

El **Teorema de Bayes** nos permite invertir probabilidades condicionales:

$$ P(B | A) = \frac{P(A | B) \cdot P(B)}{P(A)} $$

donde:

- **P(A):** Probabilidad de que una canción sea muy popular.  
- **P(B):** Probabilidad de que una canción sea explícita.  
- **P(A|B):** Probabilidad de que una canción sea muy popular dado que es explícita.  
- **P(B|A):** Probabilidad de que una canción sea explícita dado que es muy popular.  

Con el teorema de Bayes, pasamos de **P(A|B)** (ya conocida del dataset) a **P(B|A)**, usando la probabilidad total de A.

In [ ]:
# Teorema de Bayes P (B | A) = P(A | B) P(B) / P(A)
p_B_given_A = (p_A_given_B * p_B) / p_A

print(f"Si seleccionamos una canción al azar y resulta ser muy popular,\nsu probabilidad de que sea explícita es P(B|A) = {p_B_given_A:.4f}")

# Comparación
if p_B_given_A > p_B:
    print("\nSi una canción es muy popular, entonces es más probable que sea explícita.")
elif p_B_given_A < p_B:
    print("\nSi una canción es muy popular, entonces es menos probable que sea explícita.")
else:
    print("\nQue una canción sea muy popular NO cambia la probabilidad de que sea explícita.")

Si seleccionamos una canción al azar y resulta ser muy popular,
su probabilidad de que sea explícita es P(B|A) = 0.3000

Si una canción es muy popular, entonces es menos probable que sea explícita.